openapi: 3.1.0
info:
  title: Matchmaking
  description: Matchmaking
  version: 1.0.0
servers:
  - url: 'http://localhost:6543'
paths:
  /ping/:
    get:
      summary: Ping server
      operationId: ping
      responses:
        '200':
          description: The server is working correctly
          content:
            text/plain:
              example: "Hello, world!\n"
        '500':
          description: Failed to write to body
  /health/:
    get:
      summary: Get API health status
      operationId: health
      responses:
        '200':
          description: The server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-10-05T14:30:00Z"
        '500':
          description: Failed to write to body

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - status
        - timestamp