upstream matchmaking_upstream {
    server matchmaking:8000;
}

upstream bot_upstream {
    server bot:8000;
}

upstream graphgetter_upstream {
    server graphgetter:8000;
}

upstream stats_upstream {
    server stats:8000;
}

upstream stats_web_upstream {
    server stats-web:80;
}

upstream adminer_upstream {
    server adminer:8080;
}

upstream grafana_upstream {
    server grafana:3000;
}

server {
    listen 80 default_server;
    server_name _;

    location /api/matchmaking/ {
        proxy_pass http://matchmaking_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /telegram/webhook/ {
        proxy_pass http://bot_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/graphgetter/ {
        proxy_pass http://graphgetter_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/stats/ {
        proxy_pass http://stats_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name stats.*;

    location / {
        proxy_pass http://stats_web_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name adminer.*;

    location / {
        proxy_pass http://adminer_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name grafana.*;

    location / {
        proxy_pass http://grafana_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
