resolver 127.0.0.11 ipv6=off;

upstream matchmaking_upstream {
    zone matchmaking_upstream 64k;
    server matchmaking:8000 resolve;
}

upstream bot_upstream {
    zone bot_upstream 64k;
    server bot:8000 resolve;
}

upstream graphgetter_upstream {
    zone graphgetter_upstream 64k;
    server graphgetter:8000 resolve;
}

upstream stats_upstream {
    zone stats_upstream 64k;
    server stats:8000 resolve;
}

upstream api_upstream {
    zone api_upstream 64k;
    server api:8080 resolve;
}

upstream stats_web_upstream {
    zone stats_web_upstream 64k;
    server stats-web:80 resolve;
}

upstream adminer_upstream {
    zone adminer_upstream 64k;
    server adminer:8080 resolve;
}

upstream grafana_upstream {
    zone grafana_upstream 64k;
    server grafana:3000 resolve;
}

server {
    listen 80 default_server;
    server_name _;

    location /api/matchmaking/ {
        proxy_pass http://matchmaking_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /telegram/webhook/ {
        proxy_pass http://bot_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/graphgetter/ {
        proxy_pass http://graphgetter_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/stats/ {
        proxy_pass http://stats_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://api_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /stats/ {
        proxy_pass http://stats_web_upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /stats;
    }

    location /adminer/ {
        proxy_pass http://adminer_upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /adminer;
    }

    location /grafana/ {
        proxy_pass http://grafana_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /grafana;
    }
}
