from .confirm_profile import ConfirmProfileForm
from .editgame import EditGame
from .endgame import EndGame
from .mainloop import MainLoop
from .moderation import ProfileModeration
from .my_profile import MyProfile
from .participation import ParticipationForm
from .register import RegisterForm
from .startgame import StartGame
